_target_: src.models.hook_ekf_module.ModelEKFInjectModule
_partial_: True

expression: ${expression}

recon_bp: reconstructor.0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005
  weight_decay: 0.000001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

compile: False

recon_criterion:
  _target_: torch.nn.MSELoss
  reduction: none

unc_criterion:
  _target_: src.plugins.head.ekf_nll_loss.EKFGGDNLLLoss
  eps: 1.0e-8
  learn_calibration: True

epoch_phase: 10
mask_rate: 0.

sigma_z_mode: ${plugins.sigma_z.mode}
