_target_: src.models.hook_modules.ekf.ModelEKFInjectModule
_partial_: True

defaults:
  - _self_
  - ekf_net: default

expression: ${expression}

recon_bp: reconstructor.0
controller_cache_path: "data/checkpoints/controller_cache.pth" 

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

compile: False

recon_criterion:
  _target_: torch.nn.MSELoss
  reduction: none

unc_criterion:
  _target_: src.plugins.head.bayescap.BayesCap1DLoss
  reduction: none
  lambda_identity: 0.
  lambda_nll: 1.0
  identity_mode: l2
  nll_mode: paper


epoch_phase: 1
mask_rate: 0.5

source_x_range: ${plugins.sigma_z.source_x_range}
n_source_samples: ${plugins.sigma_z.n_source_samples}
