# @package _global_

defaults:
  - _self_
  - data: toy # choose datamodule with `test_dataloader()` for evaluation
  - model: toy
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

data:
  n_samples: 50000
  batch_size: 32
  num_workers: 2
  
task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: data/checkpoint_1.ckpt

logger:
  wandb:
    project: "VISHC_Uncertainty"
    name: toy_model_eval_${now:%Y-%m-%d}_${now:%H-%M-%S}