_target_: src.models.components.toy.BiModalRegressor

x1_dim: 1
x2_dim: 1
hidden_dim: 32
latent_dim: 32
fusion_hidden_dims: [64, 16, 16]
activation: gelu
dropout: 0.3
use_norm: true
use_residual: true